backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - label: "Global"
    name: "global"
    editor:
      preview: false
    files:
      - label: "League Info"
        name: "info"
        file: "assets/content/info.json"
        fields:
          - {label: name, name: name, widget: string}
          - {label: address_full, name: address_full, widget: string, hint: "Example: 333 S. Franklin Street Tampa, FL 33602"}
          - {label: address_street, name: address_street, widget: string, hint: "Example: 333 S. Franklin Street"}
          - {label: address_city, name: address_city, widget: string, hint: "Tampa"}
          - {label: Primary Phone Number, name: phone_primary, widget: string, pattern: ['[(]?\d{3}[-.)]?[ ]?\d{3}[-.]?\d{4}\b', "Must be a phone number"], hint: "(780) 434-4226"}
          - {label: Primary Email Address, name: email_primary, widget: string, pattern: ['([\w\.\-_]+)?\w+@[\w-_]+(\.\w+){1,}', "Must be an email address"]}
          - {label: Hours of Service, name: hours_of_service, widget: list}
      - label: "Social Media"
        name: "social"
        file: "assets/content/social_media.json"
        fields:
          - label: platform
            name: platform
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Link, name: link, widget: string}

  - label: "Static Pages"
    name: "static_pages"
    editor:
      preview: false
    format: 'json'
    files:
      - label: "Home Page"
        name: "home"
        file: "assets/content/static_pages/home.json"
        fields:
          - label: "Hero Section"
            name: "hero_section"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Sub Title"
                name: "sub_title"
                widget: "string"

          - label: "Membership Benefits Section"
            name: "membership_benefits_section"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Sub Title"
                name: "sub_title"
                widget: "string"
              - label: "Benefits"
                name: "benefits"
                widget: "list"
                fields:
                  - {lable: "Icon", name: "icon", widget: "string", hint: "Eg (without quotes): 'fas fa-futbol' | Must be a Font Awsome Icon. See https://fontawesome.com/ for more options" }
                  - {lable: "Title", name: "title", widget: "string" }
                  - {lable: "Description", name: "description", widget: "string" }

  - name: 'pages'
    label: 'Pages'
    format: 'json'
    folder: 'assets/content/pages'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
